runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /static
   static_dir: static
   secure: always
 
 - url: /.*
   script: app.flask_app.app
   secure: always
     
libraries:
 - name: ssl
   version: latest
